### ISSUE TITLE
Error newer version GDAL

### ISSUE THREAD

**Issue by bVdCreations** [thinkWhere/GDAL-Docker#9]
## Error installing python package of GDAL 3.0.0

when building the dockerfile based on 3.6-stretch  
I got an error on the step of 'RUN pip install GDAL>=2.2.4'
I suspect the newer version of GDAL (3.0.0) is the cause
changing the RUN command to 'RUN pip install GDAL==2.2.4'  
fixed my problem

**Comment by hunt3ri** [comment]
Thanks for the tip, will try and update the pakage soon 👍

**Comment by drtimcouper** [comment]
Please remove me from this mailing .. interesting though plot might be :-)

Tim
